name: Build & Deploy

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build
    uses: ./github/workflows/template-build.yml@main
    with:
      environment: development
      environment_short: dev
      artefact_name: frontend

  deploy:
    name: Deploy to Frontend
    uses: ./github/workflows/template-deploy.yml@main
    with:
      environment: development
      environment_short: dev
      artefact_name: frontend
    # secrets:
    #   azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
    #   azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
    #   azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
