name: Flow - Build & Deploy

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:    
    name: Build
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - name: Build
        uses: ./.github/workflows/template-build.yml
        with:
          environment: development
          environment_short: dev
          artefact_name: frontend

  deploy:    
    uses: ./.github/workflows/template-deploy.yml
    with:
      environment: development
      environment_short: dev
      artefact_name: frontend
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
