name: TESTER

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  appname: backend

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{env.appname}}
      - run: npm ci
